primev/mev-commit-docs

Primev Docs Testnet Ver 41c24e77a73e47e0966d54365efbbfc8.md, reference/provider-and-bidder-interaction-via-apis.mdx
preconfirmation not pre-confirmation
=> Remove dash in pre-conf.

concepts/mev-commit-chain/bridging-details.mdx, concepts/mev-commit-chain/chain-details.mdx, developers/contracts.mdx, mint.json
Addresses todo item and orphaned content in notion checklist
=> bridge cleanup

get-started/providers/sending-commitments.mdx, get-started/quickstart.mdx
* Updates download source for launchscript to launch.mev-commit.xyz
* consolidates docmentation
=> Moves launch script to launch.mev-commit.xyz and consolidates quickstart

get-started/faucet.mdx
* Allows user to use facuet without leaving the docs
=> Adds the faucet directly into the docs UI

concepts/bids.mdx
* Adds minor details to the bids section to describe how bid decay should be used and paramaterized
=> Adds details for Bidder Decay

concepts/bids/bidder-deposit.mdx
Tried to clarify some of the text.
=> Revise of bidder deposits.

get-started/providers/registering-a-provider.mdx, get-started/relays.mdx
Do not merge until new testnet release incorporates https://github.com/primev/mev-commit/pull/214
=> docs: update provider + relay page w.r.t builders now specifying BLS pubkey

bidder-openapi-spec.json, get-started/bidders/bidder-node-commands.mdx
Waiting for https://github.com/primev/mev-commit/pull/228 to be released
=> feat: updated bidder api spec

bidder-openapi-spec.json
Merge when bidder new version will be released
=> chore: changed bidder api

concepts/rewards-and-slashing.mdx
=> Rewards and slashing section updates

concepts/bids/bidder-deposit.mdx, get-started/bidders/bidder-node-commands.mdx
Waiting for that to go live: https://github.com/primev/mev-commit/pull/274
=> chore: updated docs according to the PR

concepts/reverting-txns.mdx, mint.json
=> feat: adds a concept section for reverting transactions

developers/testnet.mdx, snippets/testnet-addresses.mdx
Corresponds to https://github.com/primev/mev-commit/pull/339
=> PreConfCommitmentStore -> PreconfManager

bidder-openapi-spec.json, get-started/bidders/best-practices.mdx, get-started/providers/sending-commitments.mdx, get-started/quickstart.mdx, provider-openapi-spec.json
Updated the Open API specs with new fields and some corrections.
Updated bidder and provider related doc pages.
=> feat: add updated docs for v0.5.1

v0.7.0/concepts/rewards-and-slashing.mdx, v0.7.0/get-started/providers/registering-a-provider.mdx
* Gets rid of any mention of extra data as we now longer use this approach.
=> Version 0.7 Update: get's rid of mention of extra data

v0.8.0/get-started/providers/registering-a-provider.mdx
* Gives greater clarity, based on feedback received from readers
=> feat: clearer documentation around BLS keys

mint.json, v1.0.0/get-started/welcome-to-primev.mdx
- Updates docs to use new description "Primev's mev-commit makes Ethereum FAST by enabling preconfirmations and new types of mev using an encrypted mempool, enhancing yield for opted-in validators."
- Updates mint.json to remove refs to old docs versions
=> Update mint.json and welcome page

docs.json, v1.1.0/developers/fast-rpc-api.mdx, v1.1.0/get-started/fastrpc.mdx
Adding a simple page describing the API calls for the new FAST RPC.
=> Add FAST RPC API documentation.

v1.1.0/developers/networks/testnet.mdx
=> fix settlement gateway address not appearing

v1.2.x/concepts/bids/bid-structure.mdx, v1.2.x/get-started/bidders/best-practices.mdx
=> fix: update openapi and add versions
